---

minio_microk8s_servers:
  hosts:
    # a12a.mabl.online
    node-1:
      ansible_host: 83.233.237.206
      ansible_port: 622
      ansible_user: owntube_ansible
    # a12b.mabl.online
    node-2:
      ansible_host: 83.233.237.208
      ansible_port: 622
      ansible_user: owntube_ansible
    # a12c.mabl.online (formerly v1517a)
    node-3:
      ansible_host: 83.233.237.207
      ansible_port: 622
      ansible_user: owntube_ansible
    # a12d.mabl.online (formerly v1517b)
    node-4:
      ansible_host: 83.233.237.209
      ansible_port: 622
      ansible_user: owntube_ansible

...
